### ISSUE TITLE
Lock is already claimed

### ISSUE THREAD

**Issue by talset** [cycloidio/approval-resource#6] opened 2017-01-17 10:52 UTC
If the terraform apply fail, the lock release is not done but concourse.

On terraform-plan, even if we set override true on the claim, it still waiting

```
The lock warnerbros-studiotour-dev-terraform-plan is already claimed
The lock warnerbros-studiotour-dev-terraform-plan is already claimed
The lock warnerbros-studiotour-dev-terraform-plan is already claimed
The lock warnerbros-studiotour-dev-terraform-plan is already claimed
The lock warnerbros-studiotour-dev-terraform-plan is already claimed
The lock warnerbros-studiotour-dev-terraform-plan is already claimed
The lock warnerbros-studiotour-dev-terraform-plan is already claimed
The lock warnerbros-studiotour-dev-terraform-plan is already claimed
```

**Comment by Seraf** [comment] 2017-01-27 10:36
I'm closing this issue, the problem is that the override reject the approval, but when the approval is rejected, the lock wasn't released because of the pipeline.
To fix that, I added an `ensure` block on concourse pipeline to release the lock whatever happens.
We shouldn't hit this issue anymore.

**Closed as completed by Seraf** 2017-01-27 10:36 UTC
